//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.10 at 09:42:28 PM CEST 
//


package com.example.PecetCalc.util;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="komputer" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="data_ksiegowania" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="koszt_USD" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="koszt_PLN" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "komputer"
})
@XmlRootElement(name = "faktura")
public class Faktura {

    protected List<Komputer> komputer;

    /**
     * Gets the value of the komputer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the komputer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKomputer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Komputer }
     * 
     * 
     */
    public List<Komputer> getKomputer() {
        if (komputer == null) {
            komputer = new ArrayList<Komputer>();
        }
        return this.komputer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="data_ksiegowania" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="koszt_USD" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="koszt_PLN" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazwa",
        "dataKsiegowania",
        "kosztUSD",
        "kosztPLN"
    })
    public static class Komputer {

        @XmlElement(required = true)
        protected String nazwa;
        @XmlElement(name = "data_ksiegowania", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dataKsiegowania;
        @XmlElement(name = "koszt_USD")
        protected double kosztUSD;
        @XmlElement(name = "koszt_PLN")
        protected double kosztPLN;

        /**
         * Gets the value of the nazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazwa() {
            return nazwa;
        }

        /**
         * Sets the value of the nazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazwa(String value) {
            this.nazwa = value;
        }

        /**
         * Gets the value of the dataKsiegowania property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataKsiegowania() {
            return dataKsiegowania;
        }

        /**
         * Sets the value of the dataKsiegowania property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataKsiegowania(XMLGregorianCalendar value) {
            this.dataKsiegowania = value;
        }

        /**
         * Gets the value of the kosztUSD property.
         * 
         */
        public double getKosztUSD() {
            return kosztUSD;
        }

        /**
         * Sets the value of the kosztUSD property.
         * 
         */
        public void setKosztUSD(double value) {
            this.kosztUSD = value;
        }

        /**
         * Gets the value of the kosztPLN property.
         * 
         */
        public double getKosztPLN() {
            return kosztPLN;
        }

        /**
         * Sets the value of the kosztPLN property.
         * 
         */
        public void setKosztPLN(double value) {
            this.kosztPLN = value;
        }

    }

}
